# Site settings
title: Blog
email: Dashenfelder@gmail.com
description: My Blog will be a little taste of Charleston, SC life, but I will focus more on my road to becoming a developer. I will take you on a first hand look into my journey at The Iron Yard and Beyond. This is my path to building a Purpose.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: Brokensurfer
github_username:  DavidAshenfelder

# Build settings
markdown: kramdown

port: 8080
